In [1]:
import pandas as pd

In [2]:
auto_data=pd.read_csv("C:/Users/akskulka/Documents/Machine Learning/autos_imports-85.csv")

In [3]:
auto_data.shape

(205, 24)

In [4]:
dt=auto_data

In [5]:
dt.head(5)

        %symboling normalized-losses make fuel-type   aspiration num-of-doors  \
3 ?    alfa-romero               gas  std       two  convertible          rwd
  ?    alfa-romero               gas  std       two  convertible          rwd
1 ?    alfa-romero               gas  std       two    hatchback          rwd
2 164         audi               gas  std      four        sedan          fwd
  164         audi               gas  std      four        sedan          4wd

      body-style  drive-wheels  wheel-base  length  ...    num-of-cylinders  \
3 ?        front          88.6       168.8    64.1  ...                 130
  ?        front          88.6       168.8    64.1  ...                 130
1 ?        front          94.5       171.2    65.5  ...                 152
2 164      front          99.8       176.6    66.2  ...                 109
  164      front          99.4       176.6    66.4  ...                 136

       engine-size fuel-system  bore  stroke compression-ratio  \
3 ?           mpfi        3.47  2.68     9.0               111
  ?           mpfi        3.47  2.68     9.0               111
1 ?           mpfi        2.68  3.47     9.0               154
2 164         mpfi        3.19  3.40    10.0               102
  164         mpfi        3.19  3.40     8.0               115

      horsepower-peak-rpm city-mpg  highway-mpg  price
3 ?                  5000       21           27  13495
  ?                  5000       21           27  16500
1 ?                  5000       19           26  16500
2 164                5500       24           30  13950
  164                5500       18           22  17450

[5 rows x 24 columns]

In [8]:
dt=dt.replace("?",np.nan)

In [7]:
import numpy as np

In [12]:
dt=dt.replace('?',np.nan)

In [13]:
dt.head(5)

        %symboling normalized-losses make fuel-type   aspiration num-of-doors  \
3 ?    alfa-romero               gas  std       two  convertible          rwd
  ?    alfa-romero               gas  std       two  convertible          rwd
1 ?    alfa-romero               gas  std       two    hatchback          rwd
2 164         audi               gas  std      four        sedan          fwd
  164         audi               gas  std      four        sedan          4wd

      body-style  drive-wheels  wheel-base  length  ...    num-of-cylinders  \
3 ?        front          88.6       168.8    64.1  ...                 130
  ?        front          88.6       168.8    64.1  ...                 130
1 ?        front          94.5       171.2    65.5  ...                 152
2 164      front          99.8       176.6    66.2  ...                 109
  164      front          99.4       176.6    66.4  ...                 136

       engine-size fuel-system  bore  stroke compression-ratio  \
3 ?           mpfi        3.47  2.68     9.0               111
  ?           mpfi        3.47  2.68     9.0               111
1 ?           mpfi        2.68  3.47     9.0               154
2 164         mpfi        3.19  3.40    10.0               102
  164         mpfi        3.19  3.40     8.0               115

      horsepower-peak-rpm city-mpg  highway-mpg  price
3 ?                  5000       21           27  13495
  ?                  5000       21           27  16500
1 ?                  5000       19           26  16500
2 164                5500       24           30  13950
  164                5500       18           22  17450

[5 rows x 24 columns]

In [14]:
dt.describe()

,drive-wheels,wheel-base,length,width,height,num-of-cylinders,stroke,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [18]:
dt.describe(include="all")

,%symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,wheel-base,length,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower-peak-rpm,city-mpg,highway-mpg,price
count,205,205,205,203,205,205,205,205.000000,205.000000,205.000000,...,205.000000,205,201,201,205.000000,203,203,205.000000,205.000000,201
unique,22,2,2,2,5,3,2,NaN,NaN,NaN,...,NaN,8,38,36,NaN,59,23,NaN,NaN,186
top,toyota,gas,std,four,sedan,fwd,front,NaN,NaN,NaN,...,NaN,mpfi,3.62,3.40,NaN,68,5500,NaN,NaN,8495
freq,32,185,168,114,96,120,202,NaN,NaN,NaN,...,NaN,94,23,20,NaN,19,37,NaN,NaN,2
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.756585,174.049268,65.907805,...,126.907317,NaN,NaN,NaN,10.142537,NaN,NaN,25.219512,30.751220,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.021776,12.337289,2.145204,...,41.642693,NaN,NaN,NaN,3.972040,NaN,NaN,6.542142,6.886443,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.600000,141.100000,60.300000,...,61.000000,NaN,NaN,NaN,7.000000,NaN,NaN,13.000000,16.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.500000,166.300000,64.100000,...,97.000000,NaN,NaN,NaN,8.600000,NaN,NaN,19.000000,25.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.000000,173.200000,65.500000,...,120.000000,NaN,NaN,NaN,9.000000,NaN,NaN,24.000000,30.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.400000,183.100000,66.900000,...,141.000000,NaN,NaN,NaN,9.400000,NaN,NaN,30.000000,34.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,120.900000,208.100000,72.300000,...,326.000000,NaN,NaN,NaN,23.000000,NaN,NaN,49.000000,54.000000,NaN

In [19]:
dt["price"]=pd.to_numeric(dt["price"],errors="coerce")

In [20]:
dt.head(5)

        %symboling normalized-losses make fuel-type   aspiration num-of-doors  \
3 ?    alfa-romero               gas  std       two  convertible          rwd
  ?    alfa-romero               gas  std       two  convertible          rwd
1 ?    alfa-romero               gas  std       two    hatchback          rwd
2 164         audi               gas  std      four        sedan          fwd
  164         audi               gas  std      four        sedan          4wd

      body-style  drive-wheels  wheel-base  length   ...     num-of-cylinders  \
3 ?        front          88.6       168.8    64.1   ...                  130
  ?        front          88.6       168.8    64.1   ...                  130
1 ?        front          94.5       171.2    65.5   ...                  152
2 164      front          99.8       176.6    66.2   ...                  109
  164      front          99.4       176.6    66.4   ...                  136

       engine-size fuel-system  bore  stroke compression-ratio  \
3 ?           mpfi        3.47  2.68     9.0               111
  ?           mpfi        3.47  2.68     9.0               111
1 ?           mpfi        2.68  3.47     9.0               154
2 164         mpfi        3.19  3.40    10.0               102
  164         mpfi        3.19  3.40     8.0               115

      horsepower-peak-rpm city-mpg  highway-mpg    price
3 ?                  5000       21           27  13495.0
  ?                  5000       21           27  16500.0
1 ?                  5000       19           26  16500.0
2 164                5500       24           30  13950.0
  164                5500       18           22  17450.0

[5 rows x 24 columns]

In [22]:
dt=dt.drop("normalized-losses",axis=1)

In [23]:
dt.head()

        %symboling make fuel-type   aspiration num-of-doors body-style  \
3 ?    alfa-romero  std       two  convertible          rwd      front
  ?    alfa-romero  std       two  convertible          rwd      front
1 ?    alfa-romero  std       two    hatchback          rwd      front
2 164         audi  std      four        sedan          fwd      front
  164         audi  std      four        sedan          4wd      front

       drive-wheels  wheel-base  length  width   ...     num-of-cylinders  \
3 ?            88.6       168.8    64.1   48.8   ...                  130
  ?            88.6       168.8    64.1   48.8   ...                  130
1 ?            94.5       171.2    65.5   52.4   ...                  152
2 164          99.8       176.6    66.2   54.3   ...                  109
  164          99.4       176.6    66.4   54.3   ...                  136

      engine-size fuel-system  bore stroke compression-ratio  \
3 ?          mpfi        3.47  2.68    9.0               111
  ?          mpfi        3.47  2.68    9.0               111
1 ?          mpfi        2.68  3.47    9.0               154
2 164        mpfi        3.19  3.40   10.0               102
  164        mpfi        3.19  3.40    8.0               115

      horsepower-peak-rpm  city-mpg highway-mpg    price
3 ?                  5000        21          27  13495.0
  ?                  5000        21          27  16500.0
1 ?                  5000        19          26  16500.0
2 164                5500        24          30  13950.0
  164                5500        18          22  17450.0

[5 rows x 23 columns]

In [24]:
dt["horsepower-peak-rpm"].describe()

count      203
unique      23
top       5500
freq        37
Name: horsepower-peak-rpm, dtype: object

In [25]:
dt["horsepower-peak-rpm"]=pd.to_numeric(dt["horsepower-peak-rpm"],errors="coerce")

In [33]:
pd.get_dummies(dt["num-of-cylinders"])

        61   70   79   80   90   91   92   97   98   103 ...   181  183  194  \
 3 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 1 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 2 164    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   164    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 1 158    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   158    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 0 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 2 192    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 0 192    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   188    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   188    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 1 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 0 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 2 121    1    0    0    0    0    0    0    0    0    0 ...     0    0    0
 1 98     0    0    0    0    1    0    0    0    0    0 ...     0    0    0
 0 81     0    0    0    0    1    0    0    0    0    0 ...     0    0    0
 1 118    0    0    0    0    1    0    0    0    0    0 ...     0    0    0
   118    0    0    0    0    1    0    0    0    0    0 ...     0    0    0
   118    0    0    0    0    0    0    0    0    1    0 ...     0    0    0
   148    0    0    0    0    1    0    0    0    0    0 ...     0    0    0
   148    0    0    0    0    1    0    0    0    0    0 ...     0    0    0
   148    0    0    0    0    1    0    0    0    0    0 ...     0    0    0
   148    0    0    0    0    0    0    0    0    1    0 ...     0    0    0
-1 110    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 3 145    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...
-1 65     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   65     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   65     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 3 197    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   197    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-1 90     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 2 122    0    0    0    0    0    0    0    1    0    0 ...     0    0    0
   122    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   94     0    0    0    0    0    0    0    1    0    0 ...     0    0    0
   94     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   94     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   94     0    0    0    0    0    0    0    1    0    0 ...     0    0    0
   94     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 3 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   256    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
 0 ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    1    0    0 ...     0    0    0
   ?      0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-2 103    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-1 74     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-2 103    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-1 74     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-2 103    0    0    0    0    0    0    0    0    0    0 ...     0    0    0
-1 74     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   95     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   95     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   95     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   95     0    0    0    0    0    0    0    0    0    0 ...     0    0    0
   95     0    0    0    0    0    0    0    0    0    0 ...     0    0    0

        203  209  234  258  304  308  326
 3 ?      0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
 1 ?      0    0    0    0    0    0    0
 2 164    0    0    0    0    0    0    0
   164    0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
 1 158    0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
   158    0    0    0    0    0    0    0
 0 ?      0    0    0    0    0    0    0
 2 192    0    0    0    0    0    0    0
 0 192    0    0    0    0    0    0    0
   188    0    0    0    0    0    0    0
   188    0    0    0    0    0    0    0
 1 ?      0    0    0    0    0    0    0
 0 ?      0    1    0    0    0    0    0
   ?      0    1    0    0    0    0    0
   ?      0    1    0    0    0    0    0
 2 121    0    0    0    0    0    0    0
 1 98     0    0    0    0    0    0    0
 0 81     0    0    0    0    0    0    0
 1 118    0    0    0    0    0    0    0
   118    0    0    0    0    0    0    0
   118    0    0    0    0    0    0    0
   148    0    0    0    0    0    0    0
   148    0    0    0    0    0    0    0
   148    0    0    0    0    0    0    0
   148    0    0    0    0    0    0    0
-1 110    0    0    0    0    0    0    0
 3 145    0    0    0    0    0    0    0
...     ...  ...  ...  ...  ...  ...  ...
-1 65     0    0    0    0    0    0    0
   65     0    0    0    0    0    0    0
   65     0    0    0    0    0    0    0
 3 197    0    0    0    0    0    0    0
   197    0    0    0    0    0    0    0
-1 90     0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
 2 122    0    0    0    0    0    0    0
   122    0    0    0    0    0    0    0
   94     0    0    0    0    0    0    0
   94     0    0    0    0    0    0    0
   94     0    0    0    0    0    0    0
   94     0    0    0    0    0    0    0
   94     0    0    0    0    0    0    0
 3 ?      0    0    0    0    0    0    0
   256    0    0    0    0    0    0    0
 0 ?      0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
   ?      0    0    0    0    0    0    0
-2 103    0    0    0    0    0    0    0
-1 74     0    0    0    0    0    0    0
-2 103    0    0    0    0    0    0    0
-1 74     0    0    0    0    0    0    0
-2 103    0    0    0    0    0    0    0
-1 74     0    0    0    0    0    0    0
   95     0    0    0    0    0    0    0
   95     0    0    0    0    0    0    0
   95     0    0    0    0    0    0    0
   95     0    0    0    0    0    0    0
   95     0    0    0    0    0    0    0

[205 rows x 44 columns]

In [30]:
dt["num-of-cylinders"]=pd.to_numeric(dt["num-of-cylinders"],errors="coerce")

In [32]:
dt["num-of-cylinders"].dropna(inplace=True)

In [34]:
dt["num-of-cylinders"].describe()

count    205.000000
mean     126.907317
std       41.642693
min       61.000000
25%       97.000000
50%      120.000000
75%      141.000000
max      326.000000
Name: num-of-cylinders, dtype: float64

In [27]:
cylinders_dict={
    'two':2,
    'three':3,
    'four':4,
    'five':5,
    'six':6,
    'eight':8,
    'twelve':12
}

In [28]:
dt["num-of-cylinders"].replace(cylinders_dict,inplace=True)

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

In [35]:
dt.head(3)

      %symboling make fuel-type   aspiration num-of-doors body-style  \
3 ?  alfa-romero  std       two  convertible          rwd      front
  ?  alfa-romero  std       two  convertible          rwd      front
1 ?  alfa-romero  std       two    hatchback          rwd      front

     drive-wheels  wheel-base  length  width   ...     num-of-cylinders  \
3 ?          88.6       168.8    64.1   48.8   ...                  130
  ?          88.6       168.8    64.1   48.8   ...                  130
1 ?          94.5       171.2    65.5   52.4   ...                  152

    engine-size fuel-system  bore stroke compression-ratio  \
3 ?        mpfi        3.47  2.68    9.0               111
  ?        mpfi        3.47  2.68    9.0               111
1 ?        mpfi        2.68  3.47    9.0               154

    horsepower-peak-rpm  city-mpg highway-mpg    price
3 ?              5000.0        21          27  13495.0
  ?              5000.0        21          27  16500.0
1 ?              5000.0        19          26  16500.0

[3 rows x 23 columns]

In [52]:
dt=pd.get_dummies(dt,columns=["make","fuel-type","aspiration","num-of-doors","body-style","drive-wheels"])

ValueError: labels ['make' 'fuel-type' 'aspiration' 'num-of-doors' 'body-style'
 'drive-wheels'] not contained in axis

In [51]:
dt.shape

(3, 81)

In [40]:
dt=dt.dropna()

In [50]:
dt.shape

(3, 81)

In [49]:
dt[dt.isnull().any(axis=1)]

Empty DataFrame
Columns: [%symboling, wheel-base, length, width, height, curb-weight, engine-type, num-of-cylinders, engine-size, fuel-system, bore, stroke, compression-ratio, horsepower-peak-rpm, city-mpg, highway-mpg, price, make_std, make_turbo, fuel-type_four, fuel-type_two, aspiration_convertible, aspiration_hardtop, aspiration_hatchback, aspiration_sedan, aspiration_wagon, num-of-doors_4wd, num-of-doors_fwd, num-of-doors_rwd, body-style_front, body-style_rear, drive-wheels_86.6, drive-wheels_88.4, drive-wheels_88.6, drive-wheels_89.5, drive-wheels_91.3, drive-wheels_93.0, drive-wheels_93.1, drive-wheels_93.3, drive-wheels_93.7, drive-wheels_94.3, drive-wheels_94.5, drive-wheels_95.1, drive-wheels_95.7, drive-wheels_95.9, drive-wheels_96.0, drive-wheels_96.3, drive-wheels_96.5, drive-wheels_96.6, drive-wheels_96.9, drive-wheels_97.0, drive-wheels_97.2, drive-wheels_97.3, drive-wheels_98.4, drive-wheels_98.8, drive-wheels_99.1, drive-wheels_99.2, drive-wheels_99.4, drive-wheels_99.8, drive-wheels_100.4, drive-wheels_101.2, drive-wheels_102.0, drive-wheels_102.4, drive-wheels_102.7, drive-wheels_102.9, drive-wheels_103.3, drive-wheels_103.5, drive-wheels_104.3, drive-wheels_104.5, drive-wheels_104.9, drive-wheels_105.8, drive-wheels_106.7, drive-wheels_107.9, drive-wheels_108.0, drive-wheels_109.1, drive-wheels_110.0, drive-wheels_112.0, drive-wheels_113.0, drive-wheels_114.2, drive-wheels_115.6, drive-wheels_120.9]
Index: []

[0 rows x 81 columns]

In [54]:
dt.head()

      %symboling  wheel-base  length  width  height curb-weight engine-type  \
3 ?  alfa-romero       168.8    64.1   48.8    2548        dohc        four
  ?  alfa-romero       168.8    64.1   48.8    2548        dohc        four
1 ?  alfa-romero       171.2    65.5   52.4    2823        ohcv         six

     num-of-cylinders engine-size fuel-system         ...          \
3 ?               130        mpfi        3.47         ...
  ?               130        mpfi        3.47         ...
1 ?               152        mpfi        2.68         ...

    drive-wheels_106.7  drive-wheels_107.9 drive-wheels_108.0  \
3 ?                  0                   0                  0
  ?                  0                   0                  0
1 ?                  0                   0                  0

     drive-wheels_109.1  drive-wheels_110.0  drive-wheels_112.0  \
3 ?                   0                   0                   0
  ?                   0                   0                   0
1 ?                   0                   0                   0

     drive-wheels_113.0  drive-wheels_114.2  drive-wheels_115.6  \
3 ?                   0                   0                   0
  ?                   0                   0                   0
1 ?                   0                   0                   0

     drive-wheels_120.9
3 ?                   0
  ?                   0
1 ?                   0

[3 rows x 81 columns]